### ISSUE TITLE
authinfo paramerters in transport configuration is also particularly specified

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-code-registry#11]
In my case, paratera uses `2200` as ssh port and `use_login_shell` need to be set to `False` in transport configuration. So not only should we just keep computer configure in the folder, but also the transport configure file which loaded by `verdi computer configure ssh --config <url>` .
My opinion is keeping this file with minimal required parameters, and left other parameters as default. 

I am curious why not aiida setting computer by just one step, rather by `verdi computer setup` first and then `verdi computer configure ssh` ?

**Comment by ltalirz** [comment]
> My opinion is keeping this file with minimal required parameters, and left other parameters as default.

I agree with this (it was what I originally suggested in your PR, perhaps I didn't express myself clearly).
Concerning https://github.com/aiidateam/aiida-code-registry/issues/5, perhaps we should go with `fidis-setup.yml` and `fidis-configure.yml` then?

> I am curious why not aiida setting computer by just one step, rather by verdi computer setup first and then verdi computer configure ssh ?

The split of information is between the information needed for data provenance (setup) and the private, per-user information needed to connect.
However, I agree that from a user perspective, it would be better to directly call `verdi computer configure` after the `computer setup` command has finished.
If I remember correctly, we tried this once and ran into some click issues, but people may be happy to rediscuss this.

**Comment by unkcpz** [comment]
> perhaps we should go with fidis-setup.yml and fidis-configure.yml then?
I agree, if fidis-configure.yml not provided just uses default values.  I make a pr to add this information of paratera-th2 

As for [registry file](https://github.com/aiidateam/aiida-code-registry/wiki/Design-decisions#single-file-build-of-the-registry), these two aspects of information can be simply nested under same inheritance level together.

**Comment by ltalirz** [comment]
> As for registry file, these two aspects of information can be simply nested under same inheritance level together.

Right, I've updated the wiki accordingly. Feel free to reopen in case there's anything left to discuss.
