### ISSUE TITLE
Add computer-configure.yml to every computer

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-code-registry#19]
I am not sure why this hasn't happened before (was it discussed?), but I think this information would be needed to achieve a fully automated setup. What do you think @ltalirz and @unkcpz?

**Comment by unkcpz** [comment]
There is the configure file in my case (`paratera-th2-configure.yml`), I guess it does not exist in others since all default value is ok for these computers?

**Comment by ltalirz** [comment]
Yes - a fully automated setup is anyhow not possible, since the information provided at the `computer configure` level is user-specific.
As @unkcpz says, in some cases, one may want to provide a `computer-configure.yml` that overrides certain default values, while in others the defaults are fine.

**Comment by yakutovicha** [comment]
Okay, so let me know if you agree with the following:

- The file name is `computer-configure.yml`.
- The file is optional.
- It is **the only** place which may override certain default values used for the computer configuration.

**Comment by ltalirz** [comment]
Sounds good!
